spring.application.name=Database-scale-demo

spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.com.zaxxer.hikari=DEBUG

# HikariCP settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=1500
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=1800000

# minimum of timeout is 250 and min of idle is 10000
#mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8080"


#100 - 10 - 90